name: Sync Whitepaper to Astro (PR flow)

# Triggers on push to main when MD files or related assets change.
on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - 'pages/**/*.md'
      - '.github/workflows/sync-to-astro.yml'
  workflow_dispatch:  # also allows manual trigger from GitHub UI

env:
  TARGET_REPO: "apify/actor-whitepaper-web"
  TARGET_BRANCH: "sync/whitepaper-updates"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # needed for pushing changes
      pull-requests: write # needed for creating PRs

    steps:
      # Step 1: Clone the source repo (this repo) into ./source directory.
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: source

      # Step 2: Clone the target repo (Astro site) into ./target directory.
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          path: target
          token: ${{ secrets.SYNC_TOKEN }}

      # Step 3: Setup Python environment.
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: source/requirements.txt

      # Step 4: Install dependencies.
      - name: Install dependencies
        run: |
          cd source
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Step 5: Run the MD to MDX conversion script.
      - name: Run sync script
        run: |
          cd source
          python scripts/md2mdx.py
