name: Sync Whitepaper to Astro (PR flow)

# Triggers on push to main when MD files or related assets change.
on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - 'img/**'
      - '.github/workflows/sync-to-astro.yml'
  workflow_dispatch:  # also allows manual trigger from GitHub UI

env:
  TARGET_REPO: "apify/actor-whitepaper-web"
  TARGET_BRANCH: "sync/whitepaper-updates"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # needed for pushing changes
      pull-requests: write # needed for creating PRs

    steps:
      # Step 1: Clone the source repo (this repo) into ./source directory.
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: source

      # Step 2: Clone the target repo (Astro site) into ./target directory.
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          path: target
          token: ${{ secrets.SYNC_TOKEN }}

      # Step 3: Setup Python environment.
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: source/requirements.txt

      # Step 4: Install dependencies.
      - name: Install dependencies
        run: |
          cd source
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Step 5: Run the MD to MDX conversion script.
      - name: Run sync script
        run: |
          cd source
          python scripts/md2mdx.py

      # Step 6: Create or update PR with changes.
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd target
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create new branch
          git checkout -b ${{ env.TARGET_BRANCH }}

          # Only create PR if there are changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "sync: Update MDX content from whitepaper"
            git push -f origin ${{ env.TARGET_BRANCH }}

            # Create or update PR
            PR_TITLE="sync: Update MDX content from whitepaper"
            PR_BODY="Automated sync of whitepaper content to MDX format.

            This PR was automatically generated by the sync workflow."

            if gh pr view ${{ env.TARGET_BRANCH }} &>/dev/null; then
              gh pr edit ${{ env.TARGET_BRANCH }} --title "${PR_TITLE}" --body "${PR_BODY}"
            else
              gh pr create --title "${PR_TITLE}" --body "${PR_BODY}" --base main --head ${{ env.TARGET_BRANCH }}
            fi
          else
            echo "No changes to sync"
          fi
